### ISSUE TITLE
copy wiki pages from yzFolder

### ISSUE THREAD

**Issue by yzorg** [elec-alchemy/electron-plan-rfc#1]
I'm happy with the following wiki pages in yzFolder, and I'm ready for them to be copied into this project's wiki:

02 web platform
03 goals
04 electron plan roadmap

Next: I'm undecided what to put on the wiki homepage for this project ATM.  I don't want to duplicate the readme.md, nor the other wiki pages.  **\*shrug\***

**Comment by ghost** [comment]
Done :)

**Comment by yzorg** [comment]
Looks great!  Thanks!
